apiVersion: apps/v1
kind: Deployment
metadata:
  name: c8-con-pdf
  labels:
    app: c8-con-pdf
spec:
  selector:
    matchLabels:
      app: c8-con-pdf
  replicas: 1
  template:
    metadata:
      labels:
        app: c8-con-pdf
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: c8-con-pdf
          image: ghcr.io/camunda-community-hub/c8-con-pdf:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dcamunda.grpc-address=MAIN
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pea-service
spec:
  selector:
    app: pea
  ports:
    - protocol: TCP
      port: 8381
      targetPort: 8381
  type: ClusterIP