apiVersion: apps/v1
kind: Deployment
metadata:
  name: c8-con-pdf
  labels:
    app: c8-con-pdf
spec:
  selector:
    matchLabels:
      app: c8-con-pdf
  replicas: 1
  template:
    metadata:
      labels:
        app: c8-con-pdf
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: c8-con-pdf
          image: ghcr.io/camunda-community-hub/c8-con-pdf:latest
          imagePullPolicy: Always
          env:
            - name: CONNECTOR_PDF_FUNCTION
              value: io.camunda.connector.pdf.PdfFunction
            - name: CONNECTOR_PDF_TYPE
              value: c-pdf-function
            - name: CAMUNDA_CLIENT_MODE
              value: selfManaged
            - name: CAMUNDA_CLIENT_GRPCADDRESS
              value: http://camunda-zeebe-gateway:26500


          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: "1"
              memory: 512M
