apiVersion: apps/v1
kind: Deployment
metadata:
  name: c8-con-pdf
  labels:
    app: c8-con-pdf
spec:
  selector:
    matchLabels:
      app: c8-con-pdf
  replicas: 1
  template:
    metadata:
      labels:
        app: c8-con-pdf
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: c8-con-pdf
          image: ghcr.io/camunda-community-hub/process-execution-automator:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.startup.serverName=Camunda8Calcair
                -Dautomator.servers.camunda8.name=Camunda8Calcair
                -Dautomator.servers.camunda8.zeebeGrpcAddress=http://camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.taskListUrl=http://camunda-tasklist:80
                -Dautomator.servers.camunda8.taskListUserName=demo
                -Dautomator.servers.camunda8.taskListUserPassword=demo
                -Dautomator.servers.camunda8.workerExecutionThreads=2000
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pea-service
spec:
  selector:
    app: pea
  ports:
    - protocol: TCP
      port: 8381
      targetPort: 8381
  type: ClusterIP